# Generated by Django 4.2.3 on 2023-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('out_time', models.DateTimeField(verbose_name='过期时间')),
            ],
        ),
    ]
