# Generated by Django 4.2.3 on 2023-08-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_persons_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='user',
        ),
    ]
