# Generated by Django 4.2.3 on 2023-08-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinces',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
            preserve_default=False,
        ),
    ]
